(function() {
  // https://www.smashbros.com/en_US/fighter/05.html
  // https://www.smashbros.com/assets_v2/img/fighter/mario/main.png
  // https://www.smashbros.com/assets_v2/img/fighter/mario/fighter_name_sp.svg
  // https://www.smashbros.com/assets_v2/img/fighter/thumb_h/mario.png
  window.Characters = {
    mario: { name: "Mario", num: '01', align: 'left' },
    donkey_kong: { name: "Donkey Kong", num: '02', align: 'right' },
    link: { name: "Link", num: '03', align: 'right' },
    samus: { name: "Samus", num: '04', align: 'right' },
    dark_samus: { name: "Dark Samus", num: '04e', align: 'left'},
    yoshi: { name: "Yoshi", num: '05', align: 'right'},
    kirby: { name: "Kirby", num: '06', align: 'left'},
    fox: { name: "Fox", num: '07', align: 'right'},
    pikachu: { name: "Pikachu", num: '08', align: 'right'},
    luigi: { name: "Luigi", num: '09', align: 'left'},
    ness: { name: "Ness", num: '10', align: 'left'},
    captain_falcon: { name: "Captain Falcon", num: '11', align: 'right'},
    jigglypuff: { name: "Jigglypuff", num: '12', align: 'left'},
    peach: { name: "Peach", num: '13', align: 'right'},
    daisy: { name: "Daisy", num: '13e', align: 'right'},
    bowser: { name: "Bowser", num: '14', align: 'left'},
    ice_climbers: { name: "Ice Climbers", num: '15', align: 'left'},
    sheik: { name: "Sheik", num: '16', align: 'right'},
    zelda: { name: "Zelda", num: '17', align: 'left'},
    dr_mario: { name: "Dr Mario", num: '18', align: 'left'},
    pichu: { name: "Pichu", num: '19', align: 'right'},
    falco: { name: "Falco", num: '20', align: 'left'},
    marth: { name: "Marth", num: '21', align: 'right'},
    lucina: { name: "Lucina", num: '21e', align: 'left'},
    young_link: { name: "Young Link", num: '22', align: 'right'},
    ganondorf: { name: "Ganondorf", num: '23', align: 'left'},
    mewtwo: { name: "Mewtwo", num: '24', align: 'right'},
    roy: { name: "Roy", num: '25', align: 'right'},
    chrom: { name: "Chrom", num: '25e', align: 'right'},
    mr_game_and_watch: { name: "Mr Game And Watch", num: '26', align: 'right'},
    meta_knight: { name: "Meta Knight", num: '27', align: 'right'},
    pit: { name: "Pit", num: '28', align: 'right'},
    dark_pit: { name: "Dark Pit", num: '28e', align: 'right'},
    zero_suit_samus: { name: "Zero Suit Samus", num: '29', align: 'right'},
    wario: { name: "Wario", num: '30', align: 'right'},
    snake: { name: "Snake", num: '31', align: 'left'},
    ike: { name: "Ike", num: '32', align: 'left'},
    pokemon_trainer: { name: "Pokemon Trainer", num: '33-35', align: 'right'},
    diddy_kong: { name: "Diddy Kong", num: '36', align: 'right'},
    lucas: { name: "Lucas", num: '37', align: 'right'},
    sonic: { name: "Sonic", num: '38', align: 'right'},
    king_dedede: { name: "King Dedede", num: '39', align: 'right'},
    olimar: { name: "Olimar", num: '40', align: 'left'},
    lucario: { name: "Lucario", num: '41', align: 'left'},
    rob: { name: "Rob", num: '42', align: 'left'},
    toon_link: { name: "Toon Link", num: '43', align: 'right'},
    wolf: { name: "Wolf", num: '44', align: 'right'},
    villager: { name: "Villager", num: '45', align: 'right'},
    mega_man: { name: "Mega Man", num: '46', align: 'left'},
    wii_fit_trainer: { name: "Wii Fit Trainer", num: '47', align: 'right'},
    rosalina_and_luma: { name: "Rosalina And Luma", num: '48', align: 'right'},
    little_mac: { name: "Little Mac", num: '49', align: 'right'},
    greninja: { name: "Greninja", num: '50', align: 'right'},
    mii_fighter: { name: "Mii Fighter", num: '51-53', align: 'left'},
    palutena: { name: "Palutena", num: '54', align: 'right'},
    pac_man: { name: "Pac Man", num: '55', align: 'right'},
    robin: { name: "Robin", num: '56', align: 'right'},
    shulk: { name: "Shulk", num: '57', align: 'right'},
    bowser_jr: { name: "Bowser Jr", num: '58', align: 'right'},
    duck_hunt: { name: "Duck Hunt", num: '59', align: 'right'},
    ryu: { name: "Ryu", num: '60', align: 'left'},
    ken: { name: "Ken", num: '60e', align: 'right'},
    cloud: { name: "Cloud", num: '61', align: 'left'},
    corrin: { name: "Corrin", num: '62', align: 'right'},
    bayonetta: { name: "Bayonetta", num: '63', align: 'left'},
    inkling: { name: "Inkling", num: '64', align: 'right'},
    ridley: { name: "Ridley", num: '65', align: 'right'},
    simon: { name: "Simon", num: '66', align: 'right'},
    richter: { name: "Richter", num: '66e', align: 'left'},
    king_k_rool: { name: "King K Rool", num: '67', align: 'left'},
    isabelle: { name: "Isabelle", num: '68', align: 'right'},
    incineroar: { name: "Incineroar", num: '69', align: 'right'},
    piranha_plant: { name: "Piranha Plant", num: '70', align: 'right'},

    random: { name: "Random Button", num: '70', align: 'right'},
  }
})()
